- hosts: control-plane
  gather_facts: false
  tasks:
  - name: Deploy dockercoins
    command: kubectl apply -f /tmp/dockercoins.yaml
    register: deploy_result 
    tags:
    - deploy_dockercoins
    notify: Display deployment result on screen
  - name: display all resources dockercoins
    command: kubectl get all -o wide
    register: display_dockercoins
    tags:
    - display_dockercoins
  - name: Delete dockercoins
    command: kubectl delete -f /tmp/dockercoins.yaml
    tags:
    - delete_dockercoins
  
  handlers:
  - name: Display deployment result on screen
    debug:
      msg: "{{ deploy_result.stdout_lines }}"
