- hosts: control-plane
  gather_facts: false
  tasks:
  - name: copy kubeconfig to jenkins home
    shell: |
      cp -r /home/vagrant/.kube  /var/lib/jenkins
      chown -R jenkins:jenkins /var/lib/jenkins/.kube
    become: true
  - name: Deploy dockercoins
    command: kubectl apply -f dockercoins.yaml
    register: deploy_result 
    tags:
    - deploy_dockercoins
    notify: Display deployment result on screen
  - name: display all resources dockercoins
    command: kubectl get all -o wide
    register: display_dockercoins
    tags:
    - display_dockercoins
  - name: Delete dockercoins
    command: kubectl delete -f dockercoins.yaml
    tags:
    - delete_dockercoins
  
  handlers:
  - name: Display deployment result on screen
    debug:
      msg: "{{ deploy_result.stdout_lines }}"
